spring.datasource.url=jdbc:postgresql://localhost:5432/ne3madb
spring.datasource.username=postgres
spring.datasource.password=2005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.access.expiration=900000
jwt.refresh.expiration=604800000


server.port=${PORT:8040}