spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=MjjjUvTUEwQzZWinEmtuQsCijEQlLGmm
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

jwt.access.expiration=900000
jwt.refresh.expiration=604800000

pycont.url=https://pydoc-production.up.railway.app
openrouter.api.key=${OPENROUTER_API_KEY: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}
openrouter.model=${OPENROUTER_MODEL:google/gemini-2.5-flash}
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
